### ISSUE TITLE
I hope there is an option to disable scanning only on the ship

### ISSUE THREAD

**Issue by NakiriFox** [JustArion/LethalCompanyMods#1]

**Comment by JustArion** [comment]
Hi! 
Firstly, thanks for creating an issue!
Secondly, there is currently no such functionality in the current version of the mod.

I've taken the liberty of adding the functionality and updated the mod on [Thunderstore](https://thunderstore.io/c/lethal-company/p/arion/NoScanner/) too. 

Please let me know if this looks fine!

**Comment by JustArion** [comment]
The config option can be found in the `./BepInEx/config/No-Scanner.cfg` or for Thunderstore in the "Edit config" tab then searching "No-Scanner". The config option defaults to off. But you can change it to on to have it work.

**Comment by NakiriFox** [comment]
thanks :)
